name: Cypress Tests

on:
  push:
    branches: ["**"]
  pull_request:
    branches: ["**"]

jobs:
  cypress-run:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout código
        uses: actions/checkout@v3

      - name: Instalar Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 18

      - name: Instalar dependências
        run: npm ci

      - name: Instalar Cypress binário
        run: npx cypress install

      - name: Verificar instalação do Cypress
        run: npx cypress verify

      - name: Rodar testes Cypress com Dashboard
        run: npx cypress run --record --key ${{ secrets.CYPRESS_RECORD_KEY }}
